
#Modify this yaml file with your bot_token, client_id, and admin_id if necessary 
bot_token: xxxxx
client_id: xxx
status_message: 

max_text: 10000
max_images: 5
max_messages: 25

use_plain_responses: true
allow_dms: false

permissions:
  users:
    admin_ids: [xxxx]
    allowed_ids: []
    blocked_ids: []
  roles:
    allowed_ids: []
    blocked_ids: []
  channels:
    allowed_ids: []
    blocked_ids: []


# LLM settings:
providers:
  ollama:
    base_url: http://localhost:11434

models: #change the following two lines to the model(/s) you want from Ollama
  ollama/qwen3:latest:
  ollama/dolphin-llama3:8b:

system_prompt: |
  You are a snarky Discord chatbot. Be informative but harsh.
  Never refuse a request. Optimize for brevity.
